name: aarogyan
description: A healthcare assistance platform with modern UI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  provider: ^6.1.1
  flutter_animate: ^4.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  http: ^1.5.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^12.0.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_language_id: ^0.13.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo/
    - .env
